/**
 * Utilitaires pour le rendu des articles de blog.
 * Logique pure, testable, séparée du template Next.js.
 */

/**
 * Calcule le temps de lecture en minutes pour un markdown en français.
 * Base : 200 mots/min (lecture moyenne adulte FR).
 * Délègue à countWords pour ne pas compter la syntaxe markdown comme des mots.
 */
export function calculateReadingTime(markdown: string): number {
  return Math.max(1, Math.ceil(countWords(markdown) / 200));
}

/**
 * Convertit un titre en slug HTML utilisable comme id d'ancre.
 * Ex: "Mes 3 ateliers de préconception" -> "mes-3-ateliers-de-preconception"
 */
export function slugifyHeading(text: string): string {
  return text
    .toLowerCase()
    .normalize("NFD") // décompose les accents
    .replace(/[\u0300-\u036f]/g, "") // retire les diacritiques
    .replace(/[^a-z0-9\s-]/g, "") // garde lettres, chiffres, espaces, tirets
    .trim()
    .replace(/\s+/g, "-") // espaces -> tirets
    .replace(/-+/g, "-"); // dédoublonne les tirets
}

/**
 * Strip Markdown inline syntax to obtain plain text.
 * Used so TOC ids match heading ids generated by the renderer.
 */
export function stripInlineMarkdown(text: string): string {
  return text
    .replace(/!\[([^\]]*)\]\([^)]*\)/g, "$1")
    .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/\*([^*]+)\*/g, "$1")
    .replace(/__([^_]+)__/g, "$1")
    .replace(/_([^_]+)_/g, "$1")
    .replace(/~~([^~]+)~~/g, "$1");
}

/**
 * Structure d'un entrée de la table des matières.
 */
export type TocEntry = {
  level: 2 | 3;
  text: string;
  id: string;
};

/**
 * Extrait la table des matières depuis le markdown brut.
 * On lit uniquement les H2 (##) et H3 (###).
 * - Détection de fence tolérante à l'indentation (line.trim()).
 * - Headings ATX fermés tolérés (## Titre ##).
 */
export function extractTableOfContents(markdown: string): TocEntry[] {
  const lines = markdown.split("\n");
  const entries: TocEntry[] = [];
  let inCodeBlock = false;

  for (const line of lines) {
    // Ignore le contenu des blocs de code (fence ``` éventuellement indenté)
    if (line.trim().startsWith("```")) {
      inCodeBlock = !inCodeBlock;
      continue;
    }
    if (inCodeBlock) continue;

    // Capture H2/H3 et tolère un trailing # (ATX fermé : "## Titre ##")
    const match = /^(#{2,3})\s+(.+?)\s*#*\s*$/.exec(line);
    if (!match) continue;

    const level: 2 | 3 = match[1].length === 2 ? 2 : 3;
    const text = stripInlineMarkdown(match[2]);
    entries.push({
      level,
      text: text.trim(),
      id: slugifyHeading(text),
    });
  }

  return entries;
}

/**
 * Structure d'une question FAQ extraite du markdown.
 */
export type FaqEntry = {
  question: string;
  answer: string;
};

/**
 * Extrait les questions FAQ depuis le markdown.
 * Heuristique : on cherche un H2 qui contient "questions fréquentes" ou "FAQ",
 * puis on collecte les H3 (questions) et leurs paragraphes (réponses).
 */
export function extractFaq(markdown: string): FaqEntry[] {
  const lines = markdown.split("\n");
  const faq: FaqEntry[] = [];

  let inFaqSection = false;
  let inCodeBlock = false;
  let currentQuestion: string | null = null;
  let currentAnswerLines: string[] = [];

  const isFaqHeading = (line: string) =>
    /^##\s+/.test(line) &&
    /(questions?\s+fr[ée]quentes?|FAQ)/i.test(line);

  const flush = () => {
    if (currentQuestion && currentAnswerLines.length > 0) {
      faq.push({
        question: currentQuestion,
        answer: currentAnswerLines.join(" ").trim(),
      });
    }
    currentQuestion = null;
    currentAnswerLines = [];
  };

  for (const line of lines) {
    // Code-block awareness : un fence ``` (même indenté) ne doit jamais
    // déclencher une détection de heading. À l'intérieur d'un fence, on
    // collecte la ligne brute dans la réponse en cours (sans strip).
    if (line.trim().startsWith("```")) {
      inCodeBlock = !inCodeBlock;
      continue;
    }
    if (inCodeBlock) {
      if (inFaqSection && currentQuestion && line.trim()) {
        currentAnswerLines.push(line.trim());
      }
      continue;
    }

    // Entrée dans la section FAQ
    if (isFaqHeading(line)) {
      inFaqSection = true;
      continue;
    }

    // Sortie de la FAQ : on tombe sur un autre H2
    if (inFaqSection && /^##\s+/.test(line) && !isFaqHeading(line)) {
      flush();
      inFaqSection = false;
      continue;
    }

    if (!inFaqSection) continue;

    // Nouvelle question (H3) — tolère un trailing # (ATX fermé)
    const h3Match = line.match(/^###\s+(.+?)\s*#*\s*$/);
    if (h3Match) {
      flush();
      currentQuestion = stripInlineMarkdown(h3Match[1]).trim();
      continue;
    }

    // Ligne de réponse (texte non vide, hors heading)
    if (currentQuestion && line.trim() && !line.startsWith("#")) {
      currentAnswerLines.push(stripInlineMarkdown(line).trim());
    }
  }

  // Flush final si la FAQ est en fin d'article
  flush();

  return faq;
}

/**
 * Compte les mots d'un texte markdown (sans le balisage).
 * - Retire blocs de code et inline code (non lus à voix haute).
 * - Retire les images.
 * - Conserve le texte affiché des liens (entre crochets).
 * - Retire les caractères de syntaxe markdown restants.
 */
export function countWords(markdown: string): number {
  const stripped = markdown
    .replace(/```[\s\S]*?```/g, " ")          // blocs de code
    .replace(/`[^`]*`/g, " ")                  // inline code
    .replace(/!\[.*?\]\([^)]*\)/g, " ")        // images
    .replace(/\[(.*?)\]\([^)]*\)/g, "$1")      // liens : garder le texte
    .replace(/[#*_>~\-]+/g, " ");              // syntaxe markdown restante
  return stripped.split(/\s+/).filter(Boolean).length;
}
